name: rufus-crawler
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - astunparse==1.6.3
      - async-timeout==4.0.3
      - attrs==24.2.0
      - automat==24.8.1
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - constantly==23.10.4
      - cryptography==43.0.3
      - cssselect==1.2.0
      - dataclasses-json==0.6.7
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dirtyjson==1.0.8
      - diskcache==5.6.3
      - distro==1.9.0
      - exceptiongroup==1.2.2
      - fastjsonschema==2.20.0
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - frozenlist==1.4.1
      - fsspec==2024.10.0
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.1.1
      - grpcio==1.67.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.26.1
      - hyperlink==21.0.0
      - idna==3.10
      - incremental==24.7.2
      - itemadapter==0.9.0
      - itemloaders==1.3.2
      - jinja2==3.1.4
      - jiter==0.6.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - keras==3.6.0
      - langchain==0.3.4
      - langchain-community==0.3.3
      - langchain-core==0.3.12
      - langchain-huggingface==0.1.0
      - langchain-text-splitters==0.3.0
      - langsmith==0.1.136
      - libclang==18.1.1
      - llama-cloud==0.1.4
      - llama-cpp-python==0.3.1
      - llama-index==0.11.19
      - llama-index-agent-openai==0.3.4
      - llama-index-cli==0.3.1
      - llama-index-core==0.11.19
      - llama-index-embeddings-openai==0.2.5
      - llama-index-indices-managed-llama-cloud==0.4.0
      - llama-index-legacy==0.9.48.post3
      - llama-index-llms-openai==0.2.15
      - llama-index-multi-modal-llms-openai==0.2.2
      - llama-index-program-openai==0.2.0
      - llama-index-question-gen-openai==0.2.0
      - llama-index-readers-file==0.2.2
      - llama-index-readers-llama-parse==0.3.0
      - llama-parse==0.5.11
      - lxml==5.3.0
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.23.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - nbclient==0.10.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nltk==3.9.1
      - numpy==1.26.4
      - openai==0.28.0
      - opt-einsum==3.4.0
      - optree==0.13.0
      - orjson==3.10.10
      - outcome==1.3.0.post0
      - packaging==24.1
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parsel==1.9.1
      - pillow==11.0.0
      - platformdirs==4.3.6
      - playwright==1.48.0
      - propcache==0.2.0
      - protego==0.3.1
      - protobuf==4.25.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycparser==2.22
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.0
      - pydispatcher==2.0.7
      - pyee==12.0.0
      - pygments==2.18.0
      - pyopenssl==24.2.1
      - pypdf==4.3.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - queuelib==1.7.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - requests-file==2.1.0
      - requests-toolbelt==1.0.0
      - rich==13.9.3
      - rpds-py==0.20.0
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - scrapy==2.11.2
      - selenium==4.25.0
      - sentence-transformers==3.2.1
      - service-identity==24.1.0
      - six==1.16.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - sqlalchemy==2.0.36
      - striprtf==0.0.26
      - sympy==1.13.1
      - tenacity==8.5.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - tf-keras==2.17.0
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tinycss2==1.3.0
      - tldextract==5.1.2
      - tokenizers==0.20.1
      - tomli==2.0.2
      - torch==2.5.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.45.2
      - trio==0.27.0
      - trio-websocket==0.11.1
      - twisted==24.7.0
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - urllib3==2.2.3
      - w3lib==2.2.1
      - webdriver-manager==4.0.2
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.16.0
      - zope-interface==7.1.0

